# Generated by Django 5.2.1 on 2025-08-12 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="id",
        ),
        migrations.AddField(
            model_name="expense",
            name="expense_id",
            field=models.UUIDField(
                default=uuid.UUID("653e89f4-f2f5-4683-9fa8-94b514c0da17"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
