# Generated by Django 5.2.1 on 2025-08-12 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_remove_expense_id_expense_expense_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_id",
            field=models.UUIDField(
                default=uuid.UUID("8d88e649-3ae6-4983-9d93-99b4d2d0c342"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
