# Generated by Django 5.2.1 on 2025-08-12 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_expense_expense_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_id",
            field=models.UUIDField(
                default=uuid.UUID("019a3d35-ecdd-4cd6-808a-7673e683bb48"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
